default:
    image: openjdk:11-jdk

build-job:
    stage: build
    script:
        - ./gladlew assemble
test-job:
    stage: test
    script:
        - echo "Test"

deploy-job:
    stage: deploy
    script:
        - echo "Deploy"
