default:
    image: openjdk:11-jdk

build-job:
    stage: build
    script:
        - ./gradlew assemble
    artifacts:
        when: always
        paths:
            - build/libs/*.jar

test-job:
    stage: test
    script:
        - ./gradlew test

deploy-job:
    stage: deploy
    script:
        - echo "Deploy"
